FROM python:3.13-slim


WORKDIR /model

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8050

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8050"]