services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.backend
    ports:
      - "8090:8090"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./sqlite_data:/data

  model:
    build:
      context: ./model
      dockerfile: Dockerfile.model
    ports:
      - "8050:8050"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "5252:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_MODELS=llama3

  celery_worker:
    build:
      context: ./app
      dockerfile: Dockerfile.backend
    command: celery -A celery_app.app worker --loglevel=info
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - app

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - app

volumes:
  redis_data:
  ollama: