FROM python:3.13-slim


WORKDIR /model

COPY model_requirements.txt .

RUN pip install --no-cache-dir -r model_requirements.txt

COPY . .

EXPOSE 8050

CMD ["uvicorn", "model.main:app", "--reload", "--host", "0.0.0.0", "--port", "8050"]