name: Build and test app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.13
    - name: Install dep
      run: |
        python -m pip install --upgrade pip
        if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi

  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.13
    - name: Install black and isort
      run: |
        python -m pip install --upgrade pip
        python -m pip install black isort
    - name: Check import order with isort
      run: |
        isort --check-only --profile black .
    - name: Check code style with black
      run: |
        black --check --line-length 79 .

  test:
    runs-on: ubuntu-latest
    needs: [lint, style]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.13
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov
        if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi
    - name: Run tests with pytest and coverage
      run: |
        pytest --cov=. --cov-report=term --cov-fail-under=75
